//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_LoaiKhauHao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMMS_LoaiKhauHao()
        {
            this.CMMS_KhauHaoThietBi = new HashSet<CMMS_KhauHaoThietBi>();
        }
    
        public long LoaiKhauHaoId { get; set; }
        public string MaLoaiKhauHao { get; set; }
        public string TenKhauHao { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_KhauHaoThietBi> CMMS_KhauHaoThietBi { get; set; }
    }
}
