//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_GiaiPhapBaoTri
    {
        public long GiaiPhapId { get; set; }
        public string MaGiaiPhap { get; set; }
        public string MoTaGiaiPhap { get; set; }
    }
}
