//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_CumThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMMS_CumThietBi()
        {
            this.CMMS_ThietBi_CumThietBi = new HashSet<CMMS_ThietBi_CumThietBi>();
        }
    
        public long CumThietBiId { get; set; }
        public string MaCumThietBi { get; set; }
        public string TenCumThietBi { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_ThietBi_CumThietBi> CMMS_ThietBi_CumThietBi { get; set; }
    }
}
