//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_CumThietBi_BoPhanThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMMS_CumThietBi_BoPhanThietBi()
        {
            this.CMMS_BoPhan_ChiTiet = new HashSet<CMMS_BoPhan_ChiTiet>();
            this.CMMS_BoPhanThietBi_LinhKienThietBi = new HashSet<CMMS_BoPhanThietBi_LinhKienThietBi>();
            this.CMMS_ThongSoBoPhan = new HashSet<CMMS_ThongSoBoPhan>();
        }
    
        public long CumThietBi_BoPhanThietBiId { get; set; }
        public Nullable<long> ThietBi_CumThietBiId { get; set; }
        public Nullable<long> BoPhanThietBiId { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_BoPhan_ChiTiet> CMMS_BoPhan_ChiTiet { get; set; }
        public virtual CMMS_BoPhanThietBi CMMS_BoPhanThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_BoPhanThietBi_LinhKienThietBi> CMMS_BoPhanThietBi_LinhKienThietBi { get; set; }
        public virtual CMMS_ThietBi_CumThietBi CMMS_ThietBi_CumThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_ThongSoBoPhan> CMMS_ThongSoBoPhan { get; set; }
    }
}
