//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_LoaiDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMMS_LoaiDichVu()
        {
            this.CMMS_CongTyDichVu = new HashSet<CMMS_CongTyDichVu>();
            this.CMMS_ThongSoDichVu = new HashSet<CMMS_ThongSoDichVu>();
        }
    
        public long LoaiDichVuId { get; set; }
        public string MaLoaiDichVu { get; set; }
        public string TenLoaiDichVu { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_CongTyDichVu> CMMS_CongTyDichVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_ThongSoDichVu> CMMS_ThongSoDichVu { get; set; }
    }
}
