//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_KetQuaDo_BoPhan
    {
        public int ThongSoBoPhanID { get; set; }
        public System.DateTime ThoiDiemDo { get; set; }
        public Nullable<float> GiaTriDo { get; set; }
        public string NguoiDo { get; set; }
    
        public virtual CMMS_ThongSoBoPhan CMMS_ThongSoBoPhan { get; set; }
    }
}
