//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_CongTyDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMMS_CongTyDichVu()
        {
            this.CMMS_ThietBi_CongTyDichVu = new HashSet<CMMS_ThietBi_CongTyDichVu>();
        }
    
        public long CongTyDichVuId { get; set; }
        public Nullable<long> LoaiDichVu { get; set; }
        public string MaCongTy { get; set; }
        public string TenCongTy { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
    
        public virtual CMMS_LoaiDichVu CMMS_LoaiDichVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_ThietBi_CongTyDichVu> CMMS_ThietBi_CongTyDichVu { get; set; }
    }
}
