//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_DacTinhChiTiet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMMS_DacTinhChiTiet()
        {
            this.CMMS_BoPhan_ChiTiet = new HashSet<CMMS_BoPhan_ChiTiet>();
            this.CMMS_LinhKien_ChiTiet = new HashSet<CMMS_LinhKien_ChiTiet>();
        }
    
        public long DacTinhChiTietId { get; set; }
        public string MaDacTinh { get; set; }
        public string TenDacTinh { get; set; }
        public string DonViTinh { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_BoPhan_ChiTiet> CMMS_BoPhan_ChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_LinhKien_ChiTiet> CMMS_LinhKien_ChiTiet { get; set; }
    }
}
