//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_BoPhanThietBi_LinhKienThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMMS_BoPhanThietBi_LinhKienThietBi()
        {
            this.CMMS_LinhKien_ChiTiet = new HashSet<CMMS_LinhKien_ChiTiet>();
        }
    
        public long BoPhanThietBi_LinhKienThietBiId { get; set; }
        public Nullable<long> CumThietBi_BoPhanThietBiId { get; set; }
        public Nullable<long> LinhKienThietBiId { get; set; }
        public string MoTa { get; set; }
    
        public virtual CMMS_CumThietBi_BoPhanThietBi CMMS_CumThietBi_BoPhanThietBi { get; set; }
        public virtual CMMS_LinhKienThietBi CMMS_LinhKienThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_LinhKien_ChiTiet> CMMS_LinhKien_ChiTiet { get; set; }
    }
}
