//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_ThongSoBoPhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMMS_ThongSoBoPhan()
        {
            this.CMMS_KetQuaDo_BoPhan = new HashSet<CMMS_KetQuaDo_BoPhan>();
        }
    
        public int ThongSoBoPhanID { get; set; }
        public int ThongSoID { get; set; }
        public Nullable<long> CumThietBi_BoPhanThietBiId { get; set; }
        public Nullable<float> GiaTriMax { get; set; }
        public Nullable<float> GiaTriMin { get; set; }
    
        public virtual CMMS_CumThietBi_BoPhanThietBi CMMS_CumThietBi_BoPhanThietBi { get; set; }
        public virtual CMMS_DanhMuCThongSoGiamSat CMMS_DanhMuCThongSoGiamSat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_KetQuaDo_BoPhan> CMMS_KetQuaDo_BoPhan { get; set; }
    }
}
