//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_ThietBi_BoPhanQuanLy
    {
        public long ThietBi_BoPhanQunLyId { get; set; }
        public Nullable<long> ThietBiId { get; set; }
        public Nullable<long> BoPhanId { get; set; }
        public Nullable<System.DateTime> ThoiGianNhanThietBi { get; set; }
        public Nullable<System.DateTime> ThoiGianBanGiaoThietBi { get; set; }
        public Nullable<bool> QuanLy { get; set; }
    
        public virtual CMMS_ThietBi CMMS_ThietBi { get; set; }
    }
}
