//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_LinhKienThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMMS_LinhKienThietBi()
        {
            this.CMMS_BoPhanThietBi_LinhKienThietBi = new HashSet<CMMS_BoPhanThietBi_LinhKienThietBi>();
        }
    
        public long LinhKienThietBiId { get; set; }
        public string MaLinhKienThietBi { get; set; }
        public string TenLinhKienThietBi { get; set; }
        public string MoTa { get; set; }
        public Nullable<long> VatTuId { get; set; }
        public Nullable<System.DateTime> ThoiGianThayThe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_BoPhanThietBi_LinhKienThietBi> CMMS_BoPhanThietBi_LinhKienThietBi { get; set; }
    }
}
