//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_TaiLieuKyThuat_ThietBi
    {
        public long TaiLieuKyThuat_ThietBiId { get; set; }
        public Nullable<long> ThietBiId { get; set; }
        public Nullable<long> LoaiTLKTId { get; set; }
        public byte[] TapTin { get; set; }
        public string LoaiTapTin { get; set; }
    
        public virtual CMMS_LoaiTaiLieuKyThuat CMMS_LoaiTaiLieuKyThuat { get; set; }
        public virtual CMMS_ThietBi CMMS_ThietBi { get; set; }
    }
}
