//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_KhuVuc_ThietBi
    {
        public long ThietBiId { get; set; }
        public long KhuVucId { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
    
        public virtual CMMS_KhuVuc CMMS_KhuVuc { get; set; }
        public virtual CMMS_ThietBi CMMS_ThietBi { get; set; }
    }
}
