//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_BaoCaoTonThatThoiGian
    {
        public Nullable<long> TonThatID { get; set; }
        public long PhieuID { get; set; }
        public Nullable<long> ThietBiId { get; set; }
        public Nullable<System.DateTime> TuThoiGian { get; set; }
        public Nullable<System.DateTime> DenThoiGian { get; set; }
        public long NhanVienId1 { get; set; }
        public Nullable<long> NhanVienId2 { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayInBienBan { get; set; }
    }
}
