//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_TheKhiemKhuyet
    {
        public long TheId { get; set; }
        public Nullable<long> ThietBiId { get; set; }
        public Nullable<long> ThietBi_CumThietBiId { get; set; }
        public string MotaKhiemKhuyet { get; set; }
        public Nullable<int> KhiemKhuyetID { get; set; }
        public Nullable<long> NhanVienId { get; set; }
        public string MauThe { get; set; }
        public Nullable<System.DateTime> NgayTreo { get; set; }
        public Nullable<System.DateTime> NgayXuLyXong { get; set; }
        public string BienPhapXuLy { get; set; }
        public string KetQuaXuLy { get; set; }
        public Nullable<long> IDNhanVienXuLy { get; set; }
        public Nullable<int> MaSoPhieuBaoTri { get; set; }
    }
}
