//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_TrangThaiThietBi
    {
        public long ThietBiId { get; set; }
        public Nullable<long> NhomThietBiID { get; set; }
        public Nullable<long> TonThatId { get; set; }
        public Nullable<System.DateTime> ThoiGianDung { get; set; }
        public Nullable<long> NhanVienId { get; set; }
        public string GhiChuTonThat { get; set; }
        public Nullable<short> SoTheVang { get; set; }
        public Nullable<short> SoTheDo { get; set; }
        public Nullable<short> SoTheQuaHan { get; set; }
        public string ChieuTreoThe { get; set; }
        public string AmBao { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<int> H { get; set; }
        public Nullable<int> W { get; set; }
        public string TrangThai { get; set; }
        public string Caption { get; set; }
        public Nullable<long> MaSoPhieuBaoTri { get; set; }
    }
}
