//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_KhauHaoThietBi
    {
        public long KhauHaoThietBiId { get; set; }
        public Nullable<long> ThietBiId { get; set; }
        public Nullable<long> LoaiKhauHaoId { get; set; }
        public Nullable<double> GiaTriKhauHao { get; set; }
        public Nullable<double> NgayKhauHao { get; set; }
    
        public virtual CMMS_LoaiKhauHao CMMS_LoaiKhauHao { get; set; }
        public virtual CMMS_ThietBi CMMS_ThietBi { get; set; }
    }
}
