//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_ThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMMS_ThietBi()
        {
            this.CMMS_KhauHaoThietBi = new HashSet<CMMS_KhauHaoThietBi>();
            this.CMMS_KhuVuc_ThietBi = new HashSet<CMMS_KhuVuc_ThietBi>();
            this.CMMS_TaiLieuKyThuat_ThietBi = new HashSet<CMMS_TaiLieuKyThuat_ThietBi>();
            this.CMMS_ThietBi_BoPhanQuanLy = new HashSet<CMMS_ThietBi_BoPhanQuanLy>();
            this.CMMS_ThietBi_CongTyDichVu = new HashSet<CMMS_ThietBi_CongTyDichVu>();
            this.CMMS_ThietBi_CumThietBi = new HashSet<CMMS_ThietBi_CumThietBi>();
        }
    
        public long ThietBiId { get; set; }
        public string MaThietBi { get; set; }
        public string MaThietBiCu { get; set; }
        public string TenThietBi { get; set; }
        public string MoTa { get; set; }
        public Nullable<long> ChungLoaiThietBiId { get; set; }
        public string MaTaiSan { get; set; }
        public string Model { get; set; }
        public string Serial { get; set; }
        public string TinhTrang { get; set; }
        public string NgayMua { get; set; }
        public string Gia { get; set; }
        public string ThoiHanBaoHanh { get; set; }
        public string ThongSoBaoHanh { get; set; }
        public string TinhTrangMua { get; set; }
        public Nullable<bool> DungDePhanBoSanXuat { get; set; }
        public Nullable<int> Left { get; set; }
        public Nullable<int> Top { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public string Caption { get; set; }
        public string TrenLayout { get; set; }
    
        public virtual CMMS_ChungLoaiThietBi CMMS_ChungLoaiThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_KhauHaoThietBi> CMMS_KhauHaoThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_KhuVuc_ThietBi> CMMS_KhuVuc_ThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_TaiLieuKyThuat_ThietBi> CMMS_TaiLieuKyThuat_ThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_ThietBi_BoPhanQuanLy> CMMS_ThietBi_BoPhanQuanLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_ThietBi_CongTyDichVu> CMMS_ThietBi_CongTyDichVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_ThietBi_CumThietBi> CMMS_ThietBi_CumThietBi { get; set; }
    }
}
