//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_ChungLoaiThietBi_DacTinhThongSo
    {
        public long ThietBi_DacTinhThongSoId { get; set; }
        public Nullable<long> ThietBiId { get; set; }
        public Nullable<long> DacTinhThongSoId { get; set; }
    
        public virtual CMMS_DacTinhThongSo CMMS_DacTinhThongSo { get; set; }
    }
}
