//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_ThongSoDichVu
    {
        public long ThongSoDichVuId { get; set; }
        public long LoaiDichVuId { get; set; }
        public string TenGoi { get; set; }
        public string GiaTri { get; set; }
    
        public virtual CMMS_LoaiDichVu CMMS_LoaiDichVu { get; set; }
    }
}
