//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_PhieuBaoTri
    {
        public long MaSoPhieu { get; set; }
        public long ThietBiId { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<long> IdNhanVienLap { get; set; }
        public string MoTaBanDau { get; set; }
        public long ThietBi_CumThietBiId { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDauNgungMay { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDauSua { get; set; }
        public Nullable<System.DateTime> ThoiGianSuaXong { get; set; }
        public Nullable<int> SoGioTuLanHuTruoc { get; set; }
        public string KetQuaNghiemThu { get; set; }
        public Nullable<long> IdNhanVienNghiemThu { get; set; }
        public string YKienNghiemThu { get; set; }
        public Nullable<long> IdNhanVienBaoTri { get; set; }
        public string KeHoach { get; set; }
        public string DinhKy { get; set; }
        public string Nguon { get; set; }
        public Nullable<bool> Khoa { get; set; }
    }
}
