//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMS_DacTinhThongSo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMMS_DacTinhThongSo()
        {
            this.CMMS_ChungLoaiThietBi_DacTinhThongSo = new HashSet<CMMS_ChungLoaiThietBi_DacTinhThongSo>();
        }
    
        public long DacTinhThongSoId { get; set; }
        public string MaDacTinhThongSo { get; set; }
        public string TenDacTinhThongSo { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMMS_ChungLoaiThietBi_DacTinhThongSo> CMMS_ChungLoaiThietBi_DacTinhThongSo { get; set; }
    }
}
