//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDanhMucLoaiTonThat
    {
        public int MaTonThat { get; set; }
        public string TenTonThat { get; set; }
        public string LoaiMay { get; set; }
        public Nullable<bool> LaDungMayNgan { get; set; }
        public Nullable<bool> CanInBB { get; set; }
        public Nullable<int> CoKeHoach { get; set; }
        public Nullable<int> MaNhomTonThat { get; set; }
        public string LoaiDungMay { get; set; }
        public string NhomDungMay { get; set; }
        public string KieuDungMay { get; set; }
        public string CacNhomMay { get; set; }
    }
}
