//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDanhMucDonVi
    {
        public string MaDV { get; set; }
        public string TruongDonVi { get; set; }
        public string MaCN { get; set; }
        public string TenDV { get; set; }
    }
}
