//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDanhMucThietBi
    {
        public string MaMay { get; set; }
        public string TenMay { get; set; }
        public string Serial { get; set; }
        public string KichThuoc { get; set; }
        public string MaNhom { get; set; }
        public string NhaSX { get; set; }
        public string NgaySX { get; set; }
        public string NuocSX { get; set; }
        public string TinhTrangLucNhap { get; set; }
        public string NgayLapDat { get; set; }
        public string NgayHetBaoHanh { get; set; }
        public string NoiLapDat { get; set; }
        public short IDThietBi { get; set; }
    }
}
