//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbkeHoach_NhomMay
    {
        public int MaNhomMay { get; set; }
        public string TenNhomMay { get; set; }
        public Nullable<int> MucNuocMin { get; set; }
        public Nullable<int> MucNuocMax { get; set; }
        public string GhiChu { get; set; }
        public Nullable<float> TaiTrongMay { get; set; }
        public Nullable<float> SoHong { get; set; }
        public Nullable<float> LTMax { get; set; }
        public Nullable<float> SoMay { get; set; }
    }
}
