//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhieuBaoTri
    {
        public int MaSoPhieuBaoTri { get; set; }
        public string MaMay { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string NguoiLap { get; set; }
        public string MaDK { get; set; }
        public string KeHoach { get; set; }
        public string MotaTinhTrangBanDau { get; set; }
        public string TinhTrangThucTe { get; set; }
        public string NguyenNhan { get; set; }
        public Nullable<float> SoGioNgungMayKH { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public Nullable<int> NguoiBatDau { get; set; }
        public Nullable<int> NguoiKetThuc { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDauNgungMay { get; set; }
        public Nullable<System.DateTime> ThoiGianDuKienKetThuc { get; set; }
        public Nullable<System.DateTime> ThoiGianDuKienBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianBanGiaoMay { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> Khoa { get; set; }
        public Nullable<bool> Luu { get; set; }
        public Nullable<int> SoFileDinhKem { get; set; }
        public Nullable<int> DocJoinID { get; set; }
        public string NhomBaoTri { get; set; }
        public string YKienNghiemThu { get; set; }
        public string NguoiNghiemThu { get; set; }
        public string KetQuaNghiemThu { get; set; }
        public Nullable<int> NguoiThucHien { get; set; }
        public Nullable<float> SoGioTuLanHuTruoc { get; set; }
        public string Nguon { get; set; }
        public Nullable<int> Tuan { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public string ViTriHu { get; set; }
        public Nullable<int> IDHienTuong { get; set; }
        public Nullable<int> IDNguyenNhan { get; set; }
        public Nullable<int> IDCongViec { get; set; }
    }
}
