//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTheKhiemKhuyet
    {
        public int MaThe { get; set; }
        public string MaMay { get; set; }
        public string MotaKhiemKhuyet { get; set; }
        public Nullable<short> LoaiKhiemKhuyet { get; set; }
        public string NguoiTreoThe { get; set; }
        public string MauThe { get; set; }
        public Nullable<System.DateTime> NgayTreo { get; set; }
        public Nullable<System.DateTime> NgayXuLyXong { get; set; }
        public Nullable<short> TuanXuLyXong { get; set; }
        public string BienPhapXuLy { get; set; }
        public string KetQuaXuLy { get; set; }
        public string NguoiXuly { get; set; }
        public Nullable<short> Tuan { get; set; }
        public Nullable<short> Thang { get; set; }
        public Nullable<short> Nam { get; set; }
        public Nullable<int> MaSoPhieuBaoTri { get; set; }
    }
}
