//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTonThatThoiGian
    {
        public string MaMay { get; set; }
        public int MaTonThat { get; set; }
        public Nullable<System.DateTime> Tu { get; set; }
        public Nullable<System.DateTime> Den { get; set; }
        public string GhiChu { get; set; }
        public string NguoiCapNhat { get; set; }
        public int ID { get; set; }
        public Nullable<short> Thang { get; set; }
        public Nullable<short> Tuan { get; set; }
        public Nullable<short> Nam { get; set; }
        public Nullable<System.DateTime> NgayInBienBan { get; set; }
        public Nullable<int> NguoiIn { get; set; }
        public string MaDV { get; set; }
        public Nullable<long> EvenNo { get; set; }
        public Nullable<int> Checked { get; set; }
    }
}
