//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class THTDataEntities : DbContext
    {
        public THTDataEntities()
            : base("name=THTDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbDanhMucDonVi> tbDanhMucDonVis { get; set; }
        public virtual DbSet<tbDanhMucLoaiKhiemKhuyet> tbDanhMucLoaiKhiemKhuyets { get; set; }
        public virtual DbSet<tbDanhMucLoaiTonThat> tbDanhMucLoaiTonThats { get; set; }
        public virtual DbSet<tbdanhMucMay> tbdanhMucMays { get; set; }
        public virtual DbSet<tbDanhMucThietBi> tbDanhMucThietBis { get; set; }
        public virtual DbSet<tbDanhSachCongNhan> tbDanhSachCongNhans { get; set; }
        public virtual DbSet<tbDanhSachCongNhanDungMay> tbDanhSachCongNhanDungMays { get; set; }
        public virtual DbSet<tbDanhSachNVCapNhatTrangThaiThietBi> tbDanhSachNVCapNhatTrangThaiThietBis { get; set; }
        public virtual DbSet<tbPhieuBaoTri> tbPhieuBaoTris { get; set; }
        public virtual DbSet<tbTonThatThoiGian> tbTonThatThoiGians { get; set; }
        public virtual DbSet<tbTheKhiemKhuyet> tbTheKhiemKhuyets { get; set; }
        public virtual DbSet<View_DanhSachPhieuBaoTri_MachineStatus> View_DanhSachPhieuBaoTri_MachineStatus { get; set; }
    }
}
