//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BAO_TRI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DanhSachPhieuBaoTri_MachineStatus
    {
        public int MaSoPhieuBaoTri { get; set; }
        public string TenMay { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string MaDK { get; set; }
        public string KeHoach { get; set; }
        public string NhomBaoTri { get; set; }
        public string MotaTinhTrangBanDau { get; set; }
        public string TinhTrangThucTe { get; set; }
        public string NguyenNhan { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDauNgungMay { get; set; }
        public string NguoiLap { get; set; }
        public string NguoiBatDau { get; set; }
        public string NguoiKetThuc { get; set; }
    }
}
